name: DeafPal
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
  ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: YES
  ENABLE_USER_SCRIPT_SANDBOXING: YES

options:
  bundleIdPrefix: Nakama
  deploymentTarget:
    ios: "17.0"
targets:
  DeafPal:
    type: application
    platform: iOS
    sources: [DeafPal]
    # resources: [Resources]
    info:
      path: DeafPal/Info.plist
      properties:
        LSRequiresIPhoneOS: YES
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationPortraitUpsideDown,
          ]
        UISupportedInterfaceOrientations~ipad:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationPortraitUpsideDown,
          ]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: Nakama.DeafPal
      INFOPLIST_FILE: DeafPal/Info.plist
      ENABLE_TESTABILITY: YES
      ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: YES
      ENABLE_USER_SCRIPT_SANDBOXING: YES
schemes:
  DeafPal:
    build:
      targets:
        DeafPal: all
